name = "MS629-Unrestricted-Optimization"
version = "0.1.0"
license = "None"
author = "Matheus Alves de Andrade"
maintainer = "matheus.alves_prs@outlook.com"
copyright = "Copyright 2023, Matheus Alves de Andrade"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["blas", "lapack"]


[install]
library = false

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"